"""Generate 10 SkillBridge pitch DOCX documents for ConvictAI evaluation testing."""
from docx import Document
import os

OUT = "test_docs/SkillBridge"
os.makedirs(OUT, exist_ok=True)

def make(name, title, sections):
    d = Document()
    d.add_heading("SkillBridge — " + title, 0)
    d.add_paragraph("Confidential | Seed Round $3M | Singapore | June 2026")
    for h, body in sections:
        d.add_heading(h, level=1)
        d.add_paragraph(body)
    d.save(f"{OUT}/{name}")
    print(f"  {name}")

make("01_executive_summary.docx", "Executive Summary", [
    ("Company Overview", "SkillBridge is a Singapore-headquartered EdTech startup delivering an AI-powered vocational upskilling platform for blue-collar workers in Southeast Asia. We partner with manufacturers and logistics companies to reskill frontline workers in digital operations, equipment maintenance, and safety compliance — fully on mobile, in local languages."),
    ("The Problem", "Southeast Asia has 240 million blue-collar workers at risk of displacement from automation. Existing training solutions require classroom attendance, cost enterprises $800-1200 per worker, and achieve only 34% completion rates. The result: a $28B skills gap widening at 18% annually."),
    ("Our Solution", "SkillBridge delivers 10-20 minute micro-learning modules in Bahasa Indonesia, Bahasa Malaysia, Filipino, Tamil, Vietnamese, and English. Our AI tutor SkillBot adapts difficulty in real time. Employers pay $12 per worker per month (B2B SaaS). Completion rate: 89% vs 34% industry average."),
    ("Traction", "Current ARR: $380,000. 12,400 active learners. 45 paying enterprise clients including Sime Darby Berhad, Jollibee Group, DHL Express SEA, and 3M Singapore. MoM revenue growth: 22% average over last 6 months."),
    ("Funding Ask", "We are raising $3M Seed to expand to Indonesia and Vietnam, hire 8 engineers, and sign 20 new enterprise clients. Projected ARR at 12 months: $1.2M. Use of funds: Engineering 40%, Sales expansion 25%, Content production 20%, G&A 15%."),
])

make("02_team_profiles.docx", "Team & Founders", [
    ("Dr. Sarah Chen — Co-Founder & CEO", "Previously VP of Product at Google Education Singapore. PhD in Machine Learning, NUS 2017. Founded EduAI which was acquired by Pearson in 2021 for $18M. LinkedIn: linkedin.com/in/sarahchen-edtech. 12 years in EdTech product and AI. Prior exit confirms domain expertise and founder-market fit."),
    ("Raj Patel — Co-Founder & COO", "Ex-McKinsey Singapore, 6 years in Education Practice. MBA INSEAD 2016. Previously Director of Operations at SkillsFuture Singapore. LinkedIn: linkedin.com/in/rajpatel-ops. Deep employer relationships across the SEA manufacturing sector. Closed all 45 enterprise accounts personally."),
    ("Mei Lin Tan — Co-Founder & CTO", "Former Staff Engineer at Grab. Specialises in NLP and mobile-first AI systems. Built multilingual recommendation engine serving 40 million users. LinkedIn: linkedin.com/in/meiltan-cto. Holds provisional patent for adaptive micro-learning engine, Singapore application 10202312345W."),
    ("Advisory Board", "Dr. Wong Siew Ming — Former Director, Ministry of Education Singapore, 20 years experience. Priya Kapoor — Partner at Sequoia Capital India, board observer with pro-rata rights. Ahmad Fauzi — Group CHRO at Sime Darby Berhad, our largest enterprise client. Independent board with shareholder agreement, anti-dilution and tag-along rights in place."),
    ("Team Diversity", "60% of leadership team are women. Team spans 5 nationalities: Singaporean, Malaysian, Indian, Filipino, and Indonesian. All hiring uses blind resume screening. Pay equity audit in January 2026 found zero gap between genders at the same level. Employee NPS: 68."),
])

make("03_financial_projections.docx", "Financial Projections FY2026-FY2028", [
    ("Revenue Assumptions", "Growth rate assumption: 215% YoY based on current enterprise pipeline of $1.8M in signed LOIs. B2B SaaS contract average value: $144 per worker per year based on $12 per month. B2C subscription: $96 per user per year. Annual churn rate: 8% based on FY2025 cohort data. Gross margin: 74%."),
    ("Revenue Projections", "FY2026 ARR: $1.2M growing from $380K current ARR. FY2027 ARR: $3.8M. FY2028 ARR: $9.2M. Revenue split: 80% B2B enterprise SaaS, 20% B2C individual subscriptions. Total projected revenue FY2026: $800K; FY2027: $2.6M; FY2028: $6.5M."),
    ("Unit Economics", "Customer Acquisition Cost B2B: $4,200 per enterprise client. Average Contract Value: $28,800 per year. Payback period: 1.75 months. Lifetime Value: $86,400 based on 3-year average contract length. LTV to CAC ratio: 20.6x. B2C CAC: $18 per user. B2C LTV: $180. B2C LTV to CAC: 10x."),
    ("Cost Structure", "Engineering and Product: 45% of OpEx. Sales and Marketing: 30%. General and Administrative: 15%. Infrastructure: 10%. Current burn rate: $68,000 per month. Runway at current pace: 11 months. Post-Seed runway at projected burn: 26 months. EBITDA breakeven projected at $3.2M ARR in Q3 2027."),
    ("Path to Profitability", "No further fundraising required before Series A at $10M ARR. Financial statements available in data room. Revenue figures reconciled monthly against Stripe and Xero. All projections based on documented assumptions in financial model available upon request."),
])

make("04_market_research.docx", "Market Research & TAM Analysis", [
    ("Total Addressable Market", "The Southeast Asia vocational training market is valued at $28.4B in 2025, source: Korn Ferry Future of Work Report 2025. Growing at 18% CAGR driven by automation displacement of 240 million blue-collar workers, government reskilling mandates in Singapore and Malaysia, and ESG compliance pressure on manufacturers to demonstrate worker development."),
    ("Serviceable Addressable Market", "Our SAM is $4.2B covering enterprises with 50-5000 frontline workers in manufacturing, logistics, and food and beverage in Singapore, Malaysia, and Philippines. We target 3,200 companies across these three markets as our initial expansion zone."),
    ("Growth Drivers", "SkillsFuture Singapore has mandated digital literacy training for all workers by 2027. Malaysia HRD Corp provides $800 annual training subsidies per worker. Philippines TESDA signed MOU with SkillBridge in March 2026. Post-COVID normalisation of mobile learning among blue-collar workers removes the adoption barrier that blocked earlier entrants."),
    ("Competitive Gap", "Primary competitors: Coursera for Business at $400 per user per year with English only delivery, LinkedIn Learning serving professional workers only, Udemy Business as a content library without AI adaptation. No direct competitor serves blue-collar workers in 6 Southeast Asian languages with AI-powered adaptive tutoring at $144 per worker per year."),
    ("Market Validation", "12,400 learners onboarded without paid marketing. 45 enterprise clients signed through founder-led sales. NPS score of 72. Approved vendor on SkillsFuture Singapore portal enabling workers to use $500 government credits for SkillBridge courses. Government endorsement validates product-market fit."),
])

make("05_product_overview.docx", "Product Overview", [
    ("Core Platform", "Mobile-first learning app on iOS and Android with offline sync capability for factory environments with limited connectivity. AI tutor SkillBot adapts learning pace and content format in real time based on learner performance signals. Available in Bahasa Indonesia, Bahasa Malaysia, Filipino, Tamil, Vietnamese, and English."),
    ("Module Library", "340 certified micro-modules covering Equipment Maintenance and Repair, Safety and OSHA Compliance, Digital Operations including ERP system basics, Quality Control and ISO standards, and Leadership Fundamentals for team leads. Each module is 10-20 minutes in video plus interactive quiz format optimised for mobile screens."),
    ("Employer Dashboard", "Real-time workforce skills matrix showing certification progress by department and role. Automated compliance tracking with renewal reminders. API integration with major HRMS platforms including SAP SuccessFactors, Workday, and Oracle HCM. Custom reporting for ESG disclosures on workforce development."),
    ("AI Differentiation", "Our AI tutor SkillBot is trained on 2.3 million learner interactions accumulated over 14 months. It detects disengagement signals in real time and switches content format between video, interactive quiz, and simulation to re-engage learners. This drives our 89% completion rate versus the 34% industry average, a 2.6x improvement."),
    ("Intellectual Property", "Patent pending on adaptive micro-learning engine, Singapore patent application number 10202312345W, filed January 2026. Proprietary multilingual NLP model fine-tuned on trade and vocational terminology across 6 Southeast Asian languages. Dataset of 2.3 million learning interactions is a first-mover advantage that competitors cannot replicate in under 18 months."),
])

make("06_traction_metrics.docx", "Traction & KPIs", [
    ("Growth Summary", "SkillBridge launched October 2024 and reached $380K ARR in 14 months with no enterprise sales team and no paid marketing budget. All growth driven by founder-led sales and word-of-mouth referrals from satisfied enterprise clients. This demonstrates exceptional product-market fit and efficient go-to-market execution."),
    ("User Metrics June 2026", "12,400 active learners on platform. 89% course completion rate versus 34% industry average. 4.7 out of 5.0 average app store rating from 2,100 verified reviews. Daily Active Users of 5,800 representing a 47% DAU to MAU ratio. Average learner completes 3.2 modules per week."),
    ("Enterprise Client Portfolio", "45 paying enterprise clients. Average contract size $28,800 per year. Notable clients include Sime Darby Berhad Malaysia, Jollibee Group Philippines, DHL Express Southeast Asia, and 3M Singapore. NPS score 72. Zero client churn in 14 months of operation. Largest client represents 11% of ARR, no single client above 15%."),
    ("Revenue Milestones", "Month 1 launch October 2024: $9,300 MRR. Month 6 April 2025: $112,200 MRR. Month 12 October 2025: $261,400 MRR. Month 14 December 2025: $305,700 MRR. Current June 2026: $383,000 MRR. MoM revenue growth: 22% average over last 6 months. Three new enterprise LOIs signed May 2026 totalling $490,000 ACV."),
    ("Government Partnerships", "Approved vendor on SkillsFuture Singapore portal, workers can apply $500 government SkillsFuture Credit toward SkillBridge certification programs. Memorandum of Understanding signed with Philippines TESDA in March 2026 for vocational certification alignment. Active discussions with Malaysia HRD Corp for grant approval expected Q3 2026."),
])

make("07_esg_policy.docx", "ESG Policy & Impact Report", [
    ("Environmental Commitments", "SkillBridge operates carbon-neutral. All cloud infrastructure runs on AWS Singapore region which achieved 100% renewable energy in 2023. Remote-first team structure eliminates office commute emissions. Annual carbon audit conducted by SGS Certification Singapore. Scope 1 emissions: zero as we have no physical operations. Scope 2 emissions from cloud computing fully offset via Gold Standard verified carbon credits. We do not make environmental claims beyond these measured and verified metrics."),
    ("Social Impact Measurement", "We have reskilled 12,400 workers of whom 68% are in the bottom 40% income bracket by household income. An independent survey of 340 certified learners found 89% reported a wage increase within 6 months of completing certification. 51% of our learners are women. We provide 500 free annual scholarships to displaced workers through the SkillBridge Foundation, a registered charity in Singapore under charity registration number 20261234A."),
    ("Supply Chain and Labor", "All operations are conducted within Singapore, Malaysia, Philippines, Indonesia, and Vietnam — jurisdictions with established labor protection frameworks. No exposure to supply chains in jurisdictions with documented labor violations. All content creators and trainers are engaged as employees or formal contractors with written agreements, minimum wage compliance, and access to statutory benefits."),
    ("Governance Structure", "Board of Directors: Dr. Sarah Chen as CEO, Raj Patel as COO, Dr. Wong Siew Ming as Independent Director and former Ministry of Education Singapore Director with 20 years experience, Priya Kapoor as Independent Director and Sequoia Capital Partner. Full shareholder agreement in place with anti-dilution protection, tag-along rights, and information rights for all investors. Financial statements audited by Baker Tilly Singapore for FY2025. PDPA compliant with all learner data stored in Singapore."),
    ("Diversity and Inclusion", "Leadership team is 60% women and spans 5 nationalities. All hiring uses blind resume screening. Pay equity audit conducted annually — January 2026 audit found zero pay gap between genders at the same level. Named diverse leaders: Dr. Sarah Chen CEO is a woman and first-generation immigrant. Mei Lin Tan CTO is a woman with a disability. We publish our diversity metrics annually in our sustainability report."),
])

make("08_competitive_analysis.docx", "Competitive Analysis", [
    ("Market Positioning", "SkillBridge is the only AI-powered, mobile-first, multilingual vocational training platform built specifically for blue-collar workers in Southeast Asia. All major competitors target professional or knowledge workers and deliver content in English only. Our price point of $144 per worker per year compares to $380-400 for professional-focused competitors."),
    ("Competitor Weaknesses", "Coursera for Business at $400 per worker per year in English only targets university-educated professionals, not factory workers. LinkedIn Learning serves career professionals and requires strong English literacy. Udemy Business is a generic content library without AI adaptation, local language content, or blue-collar specific modules. No competitor has offline mobile capability required for factory environments."),
    ("Competitive Advantages", "Six local language delivery is a 24-month build requiring 2 million labeled training examples — competitors cannot enter quickly. Offline mobile sync for factory environments requires custom architecture. Government accreditation as SkillsFuture Singapore approved vendor took 12 months and provides a credibility barrier. Enterprise HRMS API integrations create switching costs with average 3-month implementation time."),
    ("Intellectual Property Moat", "Dataset of 2.3 million blue-collar learner interactions is proprietary and unique. No competitor has equivalent training data for vocational NLP in Southeast Asian languages. Patent pending on adaptive micro-learning engine. First-mover government partnerships with SkillsFuture Singapore and Philippines TESDA took 18 months to build."),
    ("Market Entry Barriers", "Building multilingual NLP model for vocational language requires 18-24 months of data collection under enterprise privacy agreements. Government vendor accreditation requires 12-18 months per market. Enterprise relationship network for blue-collar training requires deep industry trust built through personal relationships over years. Our 14-month head start represents a significant barrier."),
])

make("09_risk_analysis.docx", "Risk Analysis & Mitigation", [
    ("Market Risk", "Risk: Enterprise training budgets cut in economic downturn. Mitigation: 78% of contracts are tied to government subsidy schemes including SkillsFuture Singapore and Malaysia HRD Corp. These government budgets are counter-cyclical and grew 12% during COVID as governments prioritized workforce transition. Additional mitigation: 2-year contract minimums with annual pre-payment reduce in-year cancellation risk."),
    ("Technology Risk", "Risk: Large language model competitor enters market with similar product. Mitigation: Our competitive moat is the proprietary dataset of 2.3 million blue-collar learner interactions and government accreditations, not the underlying AI model. We are model-agnostic and already testing GPT-4o as an upgrade path. Government relationships and enterprise integrations cannot be replicated by a new entrant quickly."),
    ("Regulatory Risk", "Risk: Data privacy laws restrict cross-border transfer of learner data. Mitigation: All learner data is stored in country of origin on AWS regional infrastructure. Singapore data on ap-southeast-1, Malaysia data on ap-southeast-5. PDPA compliant from first day of operations. Separate data residency architecture planned for each new market before launch."),
    ("Execution Risk", "Risk: Founder concentration — loss of key co-founder. Mitigation: Three-person founding team with complementary skills ensures no single point of failure. Key-person life and disability insurance in place for all three co-founders. VP Engineering hired March 2026 as a fourth technical leader. Founder vesting schedule with 4-year cliff prevents abrupt departures. Board approval required for all material decisions."),
    ("Revenue Concentration Risk", "Top 3 clients represent 28% of ARR. Largest single client is 11% of ARR. No single client exceeds 15% of ARR threshold. Active sales pipeline includes 28 enterprise prospects across 4 markets at various stages. Enterprise client NPS of 72 indicates strong retention probability. Zero churn in 14 months of operation provides confidence in retention rates."),
])

make("10_investment_memo.docx", "Investment Memorandum", [
    ("Investment Thesis", "SkillBridge sits at the intersection of three unstoppable structural trends: 240 million Southeast Asian blue-collar workers facing automation displacement by 2030 creating mandatory demand, government mandates in Singapore and Malaysia for workforce upskilling creating subsidized and guaranteed revenue, and ESG pressure on manufacturers to demonstrate worker development programs to satisfy investor and regulatory requirements. We are the only venture-scale company solving all three with an AI-first, mobile-first, local-language platform."),
    ("Why Now and Why SkillBridge", "SkillsFuture Singapore 2027 mandate creates immediate urgency for enterprise buyers with hard compliance deadlines. Post-COVID normalization of mobile learning among blue-collar workers removes the adoption barrier that blocked earlier entrants to this market. $380K ARR proven in 14 months with zero enterprise sales headcount — now we hire and scale. Prior exit by CEO Dr. Sarah Chen at EduAI acquired by Pearson for $18M demonstrates ability to build and exit EdTech businesses in this region."),
    ("Use of Seed Funds", "$3M Seed round allocation: Engineering and AI at 40% to hire 5 engineers and 1 ML scientist for expanding SkillBot capabilities and module production. Sales expansion into Indonesia and Vietnam at 25% to hire 3 enterprise account executives with manufacturing sector relationships. Content production for 200 new modules at 20% to expand library coverage across new sectors. General and Administrative at 15% for finance, legal, and compliance infrastructure. Target milestones at 12 months: $1.2M ARR, 100 enterprise clients, Indonesia market fully launched."),
    ("Exit Scenarios", "Strategic acquirer: Pearson the company that acquired EduAI, Workday expanding HCM platform, or SAP SuccessFactors adding vocational content layer. Precedent: EduAI acquired at 12x ARR confirms buyer appetite. Private equity roll-up by global vocational training consolidators such as Adecco Group or Randstad. IPO: comparable public EdTech companies trade at 6-14x ARR. Target exit at Series B or C: $10M ARR at 10x multiple implies $100M enterprise value versus $3M Seed investment."),
    ("Terms and Contact", "Raising $3M at pre-money valuation of $15M. Priced equity round, ordinary shares. Lead investor minimum $1M with board observer seat. Follow-on tickets minimum $250K. Pro-rata rights in Series A for all Seed investors. Target close: August 31 2026. Contact: Dr. Sarah Chen, CEO, sarah@skillbridge.ai, +65 9111 2222. Raj Patel, COO, raj@skillbridge.ai, +65 9333 4444."),
])

print(f"\nAll 10 SkillBridge documents saved to: {OUT}/")
